# Site settings
title: Kevin Chen
email: kevnchn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aspiring web developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kevn-chn.github.io/" # the base hostname & protocol for your site
twitter_username:
github_username:  kevn-chn

# Build settings
markdown: kramdown

paginate: 4

author: Kevin Chen

gems: [jekyll-paginate]
